<?php

namespace Container5lEQhPW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DzPlWD2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dzPlWD2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dzPlWD2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'KuDirRepository' => ['privates', 'App\\Repository\\KuDirRepository', 'getKuDirRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'KuDirRepository' => 'App\\Repository\\KuDirRepository',
            'validator' => '?',
        ]);
    }
}
