<?php

namespace ContainerBzi0ODE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOriginalRoomsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\OriginalRoomsType' shared autowired service.
     *
     * @return \App\Form\OriginalRoomsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/OriginalRoomsType.php';

        return $container->privates['App\\Form\\OriginalRoomsType'] = new \App\Form\OriginalRoomsType();
    }
}
