<?php

namespace ContainerHPdC3rz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CUqvNoJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CUqvNoJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CUqvNoJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'SoldRepository' => ['privates', 'App\\Repository\\RepositoryPrice\\SoldRepository', 'getSoldRepositoryService', true],
        ], [
            'SoldRepository' => 'App\\Repository\\RepositoryPrice\\SoldRepository',
        ]);
    }
}
