<?php

namespace ContainerHPdC3rz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCounterpartyTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormsCounterparty\CounterpartyType' shared autowired service.
     *
     * @return \App\Form\FormsCounterparty\CounterpartyType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormsCounterparty/CounterpartyType.php';

        return $container->privates['App\\Form\\FormsCounterparty\\CounterpartyType'] = new \App\Form\FormsCounterparty\CounterpartyType();
    }
}
