<?php

namespace ContainerHPdC3rz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchSalesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormsSales\SearchSalesType' shared autowired service.
     *
     * @return \App\Form\FormsSales\SearchSalesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormsSales/SearchSalesType.php';

        return $container->privates['App\\Form\\FormsSales\\SearchSalesType'] = new \App\Form\FormsSales\SearchSalesType();
    }
}
