<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class KuDir extends \App\Entity\KuDir implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coming' => [parent::class, 'coming', null],
        "\0".parent::class."\0".'expenditure' => [parent::class, 'expenditure', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invoiceKuDir' => [parent::class, 'invoiceKuDir', null],
        "\0".parent::class."\0".'receipt_change' => [parent::class, 'receipt_change', null],
        "\0".parent::class."\0".'receipt_date' => [parent::class, 'receipt_date', null],
        "\0".parent::class."\0".'receipt_number' => [parent::class, 'receipt_number', null],
        "\0".parent::class."\0".'status_ku_dir' => [parent::class, 'status_ku_dir', null],
        'coming' => [parent::class, 'coming', null],
        'expenditure' => [parent::class, 'expenditure', null],
        'id' => [parent::class, 'id', null],
        'invoiceKuDir' => [parent::class, 'invoiceKuDir', null],
        'receipt_change' => [parent::class, 'receipt_change', null],
        'receipt_date' => [parent::class, 'receipt_date', null],
        'receipt_number' => [parent::class, 'receipt_number', null],
        'status_ku_dir' => [parent::class, 'status_ku_dir', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
