<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IdDetailsManufacturer extends \App\Entity\IdDetailsManufacturer implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'hidden' => [parent::class, 'hidden', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_axle' => [parent::class, 'id_axle', null],
        "\0".parent::class."\0".'id_body' => [parent::class, 'id_body', null],
        "\0".parent::class."\0".'id_car_brand' => [parent::class, 'id_car_brand', null],
        "\0".parent::class."\0".'id_in_stock' => [parent::class, 'id_in_stock', null],
        "\0".parent::class."\0".'id_original_number' => [parent::class, 'id_original_number', null],
        "\0".parent::class."\0".'id_part_name' => [parent::class, 'id_part_name', null],
        "\0".parent::class."\0".'id_side' => [parent::class, 'id_side', null],
        "\0".parent::class."\0".'manufacturer' => [parent::class, 'manufacturer', null],
        "\0".parent::class."\0".'manufacturers' => [parent::class, 'manufacturers', null],
        "\0".parent::class."\0".'name_detail' => [parent::class, 'name_detail', null],
        "\0".parent::class."\0".'part_number' => [parent::class, 'part_number', null],
        "\0".parent::class."\0".'part_numbers' => [parent::class, 'part_numbers', null],
        'hidden' => [parent::class, 'hidden', null],
        'id' => [parent::class, 'id', null],
        'id_axle' => [parent::class, 'id_axle', null],
        'id_body' => [parent::class, 'id_body', null],
        'id_car_brand' => [parent::class, 'id_car_brand', null],
        'id_in_stock' => [parent::class, 'id_in_stock', null],
        'id_original_number' => [parent::class, 'id_original_number', null],
        'id_part_name' => [parent::class, 'id_part_name', null],
        'id_side' => [parent::class, 'id_side', null],
        'manufacturer' => [parent::class, 'manufacturer', null],
        'manufacturers' => [parent::class, 'manufacturers', null],
        'name_detail' => [parent::class, 'name_detail', null],
        'part_number' => [parent::class, 'part_number', null],
        'part_numbers' => [parent::class, 'part_numbers', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'hidden' => true,
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
