<?php

namespace ContainerUfrQ2wL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CoyoAsOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CoyoAsO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CoyoAsO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Sections_header\\CounterpartyController::EditCounterparty' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\CounterpartyController::SalesCounterparty' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\CounterpartyController::SearchCounterparty' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\CounterpartyController::deleteCounterparty' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController::Refund' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController::SalesIncomingDocuments' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController::SalesParts' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController::SearchIncomingDocuments' => ['privates', '.service_locator.k0Abh5g', 'get_ServiceLocator_K0Abh5gService', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController::deleteInvoice' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PartNoController::deletePart' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PartNoController::editPart' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\PartNoController::salesPart' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\PartNoController::searchPart' => ['privates', '.service_locator.16FGhqR', 'get_ServiceLocator_16FGhqRService', true],
            'App\\Controller\\Sections_header\\PriceController::completeSales' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PriceController::deleteSaleList' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PriceController::editSoldPrice' => ['privates', '.service_locator.FECJdp3', 'get_ServiceLocator_FECJdp3Service', true],
            'App\\Controller\\Sections_header\\PriceController::searchPrice' => ['privates', '.service_locator.lxYgUQK', 'get_ServiceLocator_LxYgUQKService', true],
            'App\\Controller\\Sections_header\\PriceController::soldPrice' => ['privates', '.service_locator.FECJdp3', 'get_ServiceLocator_FECJdp3Service', true],
            'App\\Controller\\Sections_header\\RefundController::EditActivity' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\RefundController::EditRefund' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\RefundController::SearchRefund' => ['privates', '.service_locator.OAvFRDk', 'get_ServiceLocator_OAvFRDkService', true],
            'App\\Controller\\Sections_header\\RefundController::deleteRefund' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Sections_header\\CounterpartyController:EditCounterparty' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\CounterpartyController:SalesCounterparty' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\CounterpartyController:SearchCounterparty' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\CounterpartyController:deleteCounterparty' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController:Refund' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController:SalesIncomingDocuments' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController:SalesParts' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController:SearchIncomingDocuments' => ['privates', '.service_locator.k0Abh5g', 'get_ServiceLocator_K0Abh5gService', true],
            'App\\Controller\\Sections_header\\IncomingDocumentsController:deleteInvoice' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PartNoController:deletePart' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PartNoController:editPart' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\PartNoController:salesPart' => ['privates', '.service_locator.arTJFd8', 'get_ServiceLocator_ArTJFd8Service', true],
            'App\\Controller\\Sections_header\\PartNoController:searchPart' => ['privates', '.service_locator.16FGhqR', 'get_ServiceLocator_16FGhqRService', true],
            'App\\Controller\\Sections_header\\PriceController:completeSales' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PriceController:deleteSaleList' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\PriceController:editSoldPrice' => ['privates', '.service_locator.FECJdp3', 'get_ServiceLocator_FECJdp3Service', true],
            'App\\Controller\\Sections_header\\PriceController:searchPrice' => ['privates', '.service_locator.lxYgUQK', 'get_ServiceLocator_LxYgUQKService', true],
            'App\\Controller\\Sections_header\\PriceController:soldPrice' => ['privates', '.service_locator.FECJdp3', 'get_ServiceLocator_FECJdp3Service', true],
            'App\\Controller\\Sections_header\\RefundController:EditActivity' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\RefundController:EditRefund' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\Sections_header\\RefundController:SearchRefund' => ['privates', '.service_locator.OAvFRDk', 'get_ServiceLocator_OAvFRDkService', true],
            'App\\Controller\\Sections_header\\RefundController:deleteRefund' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Sections_header\\CounterpartyController::EditCounterparty' => '?',
            'App\\Controller\\Sections_header\\CounterpartyController::SalesCounterparty' => '?',
            'App\\Controller\\Sections_header\\CounterpartyController::SearchCounterparty' => '?',
            'App\\Controller\\Sections_header\\CounterpartyController::deleteCounterparty' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController::Refund' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController::SalesIncomingDocuments' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController::SalesParts' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController::SearchIncomingDocuments' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController::deleteInvoice' => '?',
            'App\\Controller\\Sections_header\\PartNoController::deletePart' => '?',
            'App\\Controller\\Sections_header\\PartNoController::editPart' => '?',
            'App\\Controller\\Sections_header\\PartNoController::salesPart' => '?',
            'App\\Controller\\Sections_header\\PartNoController::searchPart' => '?',
            'App\\Controller\\Sections_header\\PriceController::completeSales' => '?',
            'App\\Controller\\Sections_header\\PriceController::deleteSaleList' => '?',
            'App\\Controller\\Sections_header\\PriceController::editSoldPrice' => '?',
            'App\\Controller\\Sections_header\\PriceController::searchPrice' => '?',
            'App\\Controller\\Sections_header\\PriceController::soldPrice' => '?',
            'App\\Controller\\Sections_header\\RefundController::EditActivity' => '?',
            'App\\Controller\\Sections_header\\RefundController::EditRefund' => '?',
            'App\\Controller\\Sections_header\\RefundController::SearchRefund' => '?',
            'App\\Controller\\Sections_header\\RefundController::deleteRefund' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Sections_header\\CounterpartyController:EditCounterparty' => '?',
            'App\\Controller\\Sections_header\\CounterpartyController:SalesCounterparty' => '?',
            'App\\Controller\\Sections_header\\CounterpartyController:SearchCounterparty' => '?',
            'App\\Controller\\Sections_header\\CounterpartyController:deleteCounterparty' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController:Refund' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController:SalesIncomingDocuments' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController:SalesParts' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController:SearchIncomingDocuments' => '?',
            'App\\Controller\\Sections_header\\IncomingDocumentsController:deleteInvoice' => '?',
            'App\\Controller\\Sections_header\\PartNoController:deletePart' => '?',
            'App\\Controller\\Sections_header\\PartNoController:editPart' => '?',
            'App\\Controller\\Sections_header\\PartNoController:salesPart' => '?',
            'App\\Controller\\Sections_header\\PartNoController:searchPart' => '?',
            'App\\Controller\\Sections_header\\PriceController:completeSales' => '?',
            'App\\Controller\\Sections_header\\PriceController:deleteSaleList' => '?',
            'App\\Controller\\Sections_header\\PriceController:editSoldPrice' => '?',
            'App\\Controller\\Sections_header\\PriceController:searchPrice' => '?',
            'App\\Controller\\Sections_header\\PriceController:soldPrice' => '?',
            'App\\Controller\\Sections_header\\RefundController:EditActivity' => '?',
            'App\\Controller\\Sections_header\\RefundController:EditRefund' => '?',
            'App\\Controller\\Sections_header\\RefundController:SearchRefund' => '?',
            'App\\Controller\\Sections_header\\RefundController:deleteRefund' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
