<?php

namespace Container7Jlz4Og;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KNUuvyPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kNUuvyP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kNUuvyP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'IdDetailsManufacturerRepository' => ['privates', '.errored.nQLE4bg', NULL, 'Cannot determine controller argument for "App\\Controller\\Sections_header\\RefundController::SearchRefund()": the $IdDetailsManufacturerRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\Sections_header\\IdDetailsManufacturerRepository". Did you forget to add a use statement?'],
            'RefundDateRepository' => ['privates', 'App\\Repository\\RefundDateRepository', 'getRefundDateRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'IdDetailsManufacturerRepository' => '?',
            'RefundDateRepository' => 'App\\Repository\\RefundDateRepository',
            'doctrine' => '?',
            'validator' => '?',
        ]);
    }
}
