<?php

namespace Container7Jlz4Og;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_NQLE4bgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.nQLE4bg' shared service.
     *
     * @return \App\Controller\Sections_header\IdDetailsManufacturerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Sections_header\\RefundController::SearchRefund()": the $IdDetailsManufacturerRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\Sections_header\\IdDetailsManufacturerRepository". Did you forget to add a use statement?');
    }
}
