<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBPPB7qk\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBPPB7qk/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBPPB7qk.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBPPB7qk\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerBPPB7qk\App_KernelTestDebugContainer([
    'container.build_hash' => 'BPPB7qk',
    'container.build_id' => 'a6fdbf33',
    'container.build_time' => 1699268434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBPPB7qk');
