<?php

namespace Container4xMqaAq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LnU_ZXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lnU._zX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lnU._zX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'InvoiceRepository' => ['privates', 'App\\Repository\\RepositoryIncomingDocuments\\InvoiceRepository', 'getInvoiceRepositoryService', true],
            'KuDirRepository' => ['privates', 'App\\Repository\\RepositoryKuDir\\KuDirRepository', 'getKuDirRepositoryService', true],
            'SoldRepository' => ['privates', 'App\\Repository\\RepositoryPrice\\SoldRepository', 'getSoldRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'InvoiceRepository' => 'App\\Repository\\RepositoryIncomingDocuments\\InvoiceRepository',
            'KuDirRepository' => 'App\\Repository\\RepositoryKuDir\\KuDirRepository',
            'SoldRepository' => 'App\\Repository\\RepositoryPrice\\SoldRepository',
            'doctrine' => '?',
            'validator' => '?',
        ]);
    }
}
