<?php

namespace Container4xMqaAq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GKFi_ZUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gKFi.ZU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gKFi.ZU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'RefundDateRepository' => ['privates', 'App\\Repository\\RepositoryRefund\\RefundDateRepository', 'getRefundDateRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'RefundDateRepository' => 'App\\Repository\\RepositoryRefund\\RefundDateRepository',
            'validator' => '?',
        ]);
    }
}
