<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4W1M3Hc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4W1M3Hc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4W1M3Hc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4W1M3Hc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4W1M3Hc\App_KernelDevDebugContainer([
    'container.build_hash' => '4W1M3Hc',
    'container.build_id' => '6119b1c7',
    'container.build_time' => 1706024956,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4W1M3Hc');
