<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcqqOgo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcqqOgo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcqqOgo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcqqOgo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcqqOgo\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcqqOgo',
    'container.build_id' => 'a71d201d',
    'container.build_time' => 1703865326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcqqOgo');
