<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfrQ2wL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfrQ2wL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUfrQ2wL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUfrQ2wL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUfrQ2wL\App_KernelDevDebugContainer([
    'container.build_hash' => 'UfrQ2wL',
    'container.build_id' => '3f075ac0',
    'container.build_time' => 1702914401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUfrQ2wL');
